-- Navy Baseball: first real program (tenant #1), 2026-07-06
insert into programs (name, slug, colors)
values ('Navy Baseball', 'navy', '{"primary":"#14233B","accent":"#C8A24B"}')
on conflict (slug) do nothing;

insert into program_config (program_id)
select id from programs where slug = 'navy'
on conflict do nothing;

-- Navy's travel-program tiers, seeded from the cleaned list
insert into program_travel_tiers (program_id, travel_id, tier)
select p.id, t.id, v.tier
from (values
  ('5 star mafia', '3'),
  ('5 star national west', '3'),
  ('5 star texas', '3'),
  ('643 dp', '1'),
  ('9ers', '2'),
  ('9th inning royals', '3'),
  ('aba', '3'),
  ('action', '3'),
  ('all star baseball academy', '2'),
  ('alpha', '1'),
  ('artillery', '1'),
  ('atl lightning', '3'),
  ('austin wings', '3'),
  ('banditos', '1'),
  ('baseball u ct', '2'),
  ('baseball u pa', '2'),
  ('baum bat', '2'),
  ('beast', '3'),
  ('bo jackson elite', '3'),
  ('body armour titans', '2'),
  ('boston prime', '1'),
  ('bpa', '2'),
  ('bpc', '2'),
  ('bushback', '3'),
  ('c35', '2'),
  ('canes', '2'),
  ('canes southwest', '3'),
  ('canes tri state', '1'),
  ('canes west', '2'),
  ('cangelosi', '1'),
  ('cba california', '1'),
  ('cba orioles', '1'),
  ('cbu', '1'),
  ('cherry creek', '3'),
  ('chicago scouts', '1'),
  ('clubhouse', '1'),
  ('coastal prospects', '3'),
  ('cpba', '3'),
  ('ct grind', '2'),
  ('dallas mustangs', '3'),
  ('dallas patriots', '3'),
  ('dallas tigers', '1'),
  ('devine', '3'),
  ('diamond jacks', '2'),
  ('dirtbags', '1'),
  ('dulin dodgers', '1'),
  ('east bay bandits', '3'),
  ('east coast sox', '3'),
  ('east cobb astros', '1'),
  ('ec lumberjacks', '2'),
  ('elite baseball training', '1'),
  ('elite squad', '2'),
  ('fl burn', '1'),
  ('fl dodgers', '3'),
  ('florida burn', '1'),
  ('ga bombers', '3'),
  ('gamers', '3'),
  ('gbg california', '1'),
  ('gbg northeast', '1'),
  ('ghost', '1'),
  ('grb northstar', '3'),
  ('hawaii elite', '3'),
  ('hitters', '3'),
  ('hunter pence', '3'),
  ('indiana bulls', '3'),
  ('indiana mustangs', '3'),
  ('indiana prospects', '3'),
  ('jeff smith baseball', '3'),
  ('keystone state bombers', '3'),
  ('legacy baseball', '3'),
  ('locked in expos', '2'),
  ('lonestar baseball', '3'),
  ('lynx', '1'),
  ('marucci elite', '3'),
  ('matt duffy baseball', '2'),
  ('metro west sports devils', '2'),
  ('mid atlantic red sox', '2'),
  ('mvp new england', '1'),
  ('mvp steel', '3'),
  ('neb', '1'),
  ('new level', '3'),
  ('next level baseball', '3'),
  ('nokona', '1'),
  ('nor''easters', '3'),
  ('norcal u', '1'),
  ('northeast gators', '2'),
  ('northeast pride', '2'),
  ('nova premier', '2'),
  ('o''s scout', '3'),
  ('on deck', '3'),
  ('original fl pokers', '2'),
  ('orlando scorpions', '1'),
  ('ostingers', '2'),
  ('pa bellringers', '3'),
  ('pa rebels', '3'),
  ('pfa', '2'),
  ('philly bandits', '3'),
  ('primetime aces', '2'),
  ('prosteck', '3'),
  ('richmond braves', '1'),
  ('rockies', '3'),
  ('route 2 blue sox', '3'),
  ('sandlot', '2'),
  ('sba bolts', '1'),
  ('scorpions team easton', '1'),
  ('sd show', '3'),
  ('service baseball', '3'),
  ('show new england', '2'),
  ('slammers', '1'),
  ('smartense', '3'),
  ('socal birds', '2'),
  ('socal bombers', '2'),
  ('socal giants', '2'),
  ('south charlotte panthers', '2'),
  ('south texas sliders', '3'),
  ('stacked', '3'),
  ('stars baseball', '1'),
  ('tb socal', '2'),
  ('tbt texas', '3'),
  ('test', '2'),
  ('texas oilers', '3'),
  ('texas stix', '3'),
  ('texas twelve', '1'),
  ('tidewater drillers', '2'),
  ('tkr reds', '3'),
  ('top tier il', '3'),
  ('top tier roos', '2'),
  ('tpa nationals', '2'),
  ('tri state arsenal', '1'),
  ('trosky', '1'),
  ('ubc', '3'),
  ('us elite', '2'),
  ('usa prime', '3'),
  ('west coast blackdogs', '3'),
  ('wildcatters', '1'),
  ('wladyka', '3'),
  ('wow factor', '3'),
  ('wow factor nation', '3'),
  ('wow factor north', '3'),
  ('wow factor northeast', '2'),
  ('wow factor texas', '3'),
  ('x team', '3')
) as v(name, tier)
join programs p on p.slug = 'navy'
join travel_programs t on t.name = v.name
on conflict (program_id, travel_id) do nothing;

select (select count(*) from programs where slug='navy') as navy_program,
       (select count(*) from program_travel_tiers ptt join programs p on p.id=ptt.program_id where p.slug='navy') as navy_tiers;
